### ISSUE TITLE
root must be an existing path when loading  NES Music Database

### ISSUE THREAD

**Issue by jamesliu** [salu133445/muspy#16]
![Screen Shot 2020-11-18 at 7 13 30 PM](https://user-images.githubusercontent.com/41763/99616656-810e4880-29d2-11eb-9808-a8f5c5bef28d.png)

**Comment by salu133445** [comment]
Hi, the code won't create the root directory automatically. You have to create the root directory before running the code snippet. Thanks.

**Comment by jamesliu** [comment]
I see. That is the design decision. Thanks.
