### ISSUE TITLE
add "control_change" message events to music representation

### ISSUE THREAD

**Issue by jeremyjordan** [salu133445/muspy#17]
I'm interested in training a language model which can predict when to use the sustain pedal in addition to the standard pitch events. The [MIDI specification](https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2) defines the use of sustain as a `control_change` message with a value of <63 denoting off and ≥64 denoting on.

Looking through the `muspy` library, it doesn't look like there's existing support for `control_change` messages. Would you be open to the addition of this feature? Do you have a preferred design?

I believe the feature would involve:
- add a `control_changes` attribute to `muspy.Track`
- modify `muspy.inputs.midi.from_mido` to handle control change events
- modify `to_event_representation` and `from_event_representation` to include `control_change` events (would you like to make this generic or just directly support the sustain pedal event?)

**Comment by salu133445** [comment]
Yes, that would be awesome! I don't currently have time to work on this, but it shouldn't be too complicated to implement this feature.

- Sounds good!
- And `muspy.outputs.mido.to_mido` as well.
- I think either is fine for now. If we want to make it generic, we might want to include only CC 64-69 in the event representation, though I don't how common are CC 65-69 being used.

Reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2

**Comment by jeremyjordan** [comment]
Sounds good,  I'll open a PR when I find time to work on this feature!
