### ISSUE TITLE
function to_pytorch_dataset() different performance between document and fact

### ISSUE THREAD

**Issue by ldzhangyx** [salu133445/muspy#2]
document description: 
> representation (str, optional) – Target representation. Supported values are ‘event’, ‘note’, ‘pianoroll’, ‘monotoken’ and ‘polytoken’.
(https://salu133445.github.io/muspy/doc/muspy.html#muspy.Dataset.to_pytorch_dataset)

If I use monotoken as the parameter then:

> ValueError: `kind` must be one of 'pitch', 'piano-roll', 'event' and 'note'.

**Comment by salu133445** [comment]
Thanks for reporting this. The documentation has been updated. Fixed in 1c50638.
