### ISSUE TITLE
Duplicate velocity events

### ISSUE THREAD

**Issue by cifkao** [salu133445/muspy#21]
We are checking if the velocity of the current note is the same as the velocity of the last note:
https://github.com/salu133445/muspy/blob/c292d8857cea58493a07ded666afc63ec78b9f3b/muspy/outputs/event.py#L88
This means we will get duplicate velocity events if the velocity changes but stays in the same quantization bin. We should instead compute the *quantized* velocity and compare that.

**Comment by salu133445** [comment]
Thanks for reporting!
