### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by cifkao** [salu133445/muspy#39]
- [x] Allow passing open files (`TextIO`) instead of paths to `save_*` and `load_*` methods/functions to facilitate compression.
- [x] Add support for some common compression method(s) (e.g. gzip, lzma) for JSON and (maybe) YAML via an optional `compression` parameter.
- [x] Make `save` and `load` recognize compressed file extensions, e.g. `.json.gz`

For discussion and efficiency benchmark, see #36.

**Comment by salu133445** [comment]
Opened files are now supported by `save_json` and `save_yaml` (8a485b1).

**Comment by salu133445** [comment]
Opened files are now supported by `load_json` and `load_yaml` (bcf7a39).

**Comment by salu133445** [comment]
Gzipped JSON and YAML files (`.json.gz` and `.yaml.gz`) are now supported by `load` and `save` (27d26b6).

**Comment by salu133445** [comment]
Another TODO is to expose the `compressed` argument to the dataset module (e.g., `muspy.Dataset.convert`).

**Comment by salu133445** [comment]
Most features are now supported.
