### ISSUE TITLE
Convert time to seconds in to_pretty_midi

### ISSUE THREAD

**Issue by cifkao** [salu133445/muspy#41]
`to_pretty_midi` should convert time to seconds as per the [TODO in the code](https://github.com/salu133445/muspy/blob/f796f2b22e1089dec101e0194df6dbe34fdf3ccb/muspy/outputs/midi.py#L402).

**Comment by salu133445** [comment]
This has already been fixed in e83e302 actually.

**Comment by cifkao** [comment]
Oh, then I must have been looking at the old version...
