### ISSUE TITLE
about  muspy.key_signature

### ISSUE THREAD

**Issue by cythc** [salu133445/muspy#5]
Hello! 
I read a .mid file and write it into a output file without any changes, but it raise the error as follow:
        key=PITCH_NAMES[key_signature.root] + suffix,
        TypeError: list indices must be integers or slices, not str

my code is :
music = muspy.read_midi(data_path)
muspy.write_midi(music,output)

And I find that the type of music.key_signature[].root is str, but in Muspy Doc, the type should be int 
![image](https://user-images.githubusercontent.com/32976364/94337281-ec175080-001b-11eb-9045-b61a21ef55c9.png)

I wonder know why!

**Comment by salu133445** [comment]
Thanks for reporting. It is actually a bug, and has been fixed in 2e8c253.
