### ISSUE TITLE
A question in muspy.show_score()

### ISSUE THREAD

**Issue by rgb000000** [salu133445/muspy#50]
Does the staff generated by muspy.show_score() only display half-beat notes?
![test](https://user-images.githubusercontent.com/26807648/104420619-197d0f80-55b5-11eb-84fc-82fd2f6bbf1b.png)
![real_scale](https://user-images.githubusercontent.com/26807648/104420943-9d36fc00-55b5-11eb-974a-5bbd21d7331b.png)

**Comment by salu133445** [comment]
Not sure what you mean by half-beat notes. The default behavior is to match the actual note length by tied notes. You can downsample the music by `music.adjust_resolution()` if you find it annoying.

**Comment by rgb000000** [comment]
Thanks for your reply！
