### ISSUE TITLE
Recursive methods only descend into list attributes

### ISSUE THREAD

**Issue by cifkao** [salu133445/muspy#52]
There is a potential issue which seems to be common to all recursive methods of `ComplexBase`: they only recurse into list attributes. I.e. if you have a non-list attribute whose value contains list attributes, these list attributes will be invisible to those methods.

The only place where it could currently matter seems to be `metadata.creators`, but `Metadata` is not actually a `ComplexBase` (though perhaps it should be?).

Also consider that there could be a similar problem if a subclass of `Base` (but not `ComplexBase`) has some `ComplexBase` attributes (this should probably be forbidden).

**Comment by salu133445** [comment]
The current way for implementing these recursive functions is only to avoid repetitive code in our codebase. Extending them to other functionality will certainly cause unexpected behaviors, yet is out of our control to be honest.

**Comment by salu133445** [comment]
I am closing this issue for now. Let me know if there is indeed any real use case when such implementation could be problematic.
