### ISSUE TITLE
Example for extracting Chord object

### ISSUE THREAD

**Issue by ruathudo** [salu133445/muspy#6]
Hi, I see the Chord class in the documentation but not sure how to use them with provided dataset. 
For example, in wikifonia dataset, it is marked with chord support. Can you give a simple example how to extract the chords information for that dataset? Thanks.

**Comment by salu133445** [comment]
Hi, parsing chords from a MusicXML file has not been implemented yet.

**Comment by salu133445** [comment]
Somewhat relevant - maybe we should make `Chord.pitches` and `Chord.pitches_str` sets?

**Comment by ruathudo** [comment]
This sounds great. Also when parsing the notes, can we keep the silent notes available?

**Comment by salu133445** [comment]
> This sounds great. Also when parsing the notes, can we keep the silent notes available? 

You mean notes with zero velocity? If so, that would be tricky - note-ons with zero velocity are usually considered equivalent to note-offs.
