### ISSUE TITLE
Fantastic job, neighbor!

### ISSUE THREAD

**Issue by asigalov61** [salu133445/muspy#7]
Hey Hao-Wen,

Thank you so much for your work and for the brilliant muspy! It's very cute, capable, and outright perfect IMHO, especially for ML/DL music stuff that I am into.

Just wanted to say hi and thank you for doing all this. It is most helpful and most practical.

Please check out my Github as you may find it interesting as I love music and computers very much.

I have just started using muspy and it's just great. I am going to write for us all a nice and most capable MIDI2NL processor which will be dependent on your work so please know it and please continue developing it as it is very needed.

Most sincerely,

Aleksandr Sigalov

Alex

**Comment by salu133445** [comment]
Hi Alex, Thanks for the comments. Glad to know that you are using MusPy on your project. Feel free to open an issue or send a pull request for bugs or feature requests. Thanks!
